AGENCE/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using R.DAL.Context;

namespace AGENCE.Controllers
{
    public class DefaultController : Controller
    {
        R.DAL.Context.R_DB_Entities db = new R.DAL.Context.R_DB_Entities();
        public ActionResult Index()
        {
            ViewBag.id = (Int32)Session["id"];
            int ID = (Int32)Session["id"];
            var user = db.agencies.Where(i => i.id == ID).FirstOrDefault();

            

            return View();
        }


        public ActionResult Travel()
        {
            int ID = (Int32)Session["id"];
            var travel_list = db.travels.Where(i => i.id_agency == ID);
            return View(travel_list);
        }
        public ActionResult Create()
        {
            var m = new travel();
            int ID = (Int32)Session["id"];
            ViewBag.beginning = new SelectList(db.villes, "id", "ville_name");
            ViewBag.destination = new SelectList(db.villes, "id", "ville_name");
            return View(m);
        }

        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public async Task<ActionResult> Create(travel tr)
        {
            int ID = (Int32)Session["id"];
            R.DAL.Context.travel TRAVEL = new R.DAL.Context.travel()
            {
                id_agency = ID,
                beginning = tr.beginning,
                destination = tr.destination,
                date_start = tr.date_start,
                date_arrive = tr.date_arrive,

            };

            db.travels.Add(TRAVEL);
            db.SaveChanges();

            ViewBag.beginning = new SelectList(db.villes, "id", "ville_name",tr.beginning);
            ViewBag.destination = new SelectList(db.villes, "id", "ville_name",tr.destination);
            return RedirectToAction("Travel");
        }

        public async Task<ActionResult> Edit(int? id)
        {
            
            Session["identity"] = id.Value;
            ViewBag.id = id.Value;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            travel TRAVEL = await db.travels.FindAsync(id);
            if (TRAVEL == null)
            {
                return HttpNotFound();
            }
            int ID = (Int32)Session["id"];
            if (TRAVEL.id_agency != ID)
            {
                return HttpNotFound();
            }
            ViewBag.beginning = new SelectList(db.villes, "id", "ville_name", TRAVEL.beginning);
            ViewBag.destination = new SelectList(db.villes, "id", "ville_name", TRAVEL.destination);
            return View(TRAVEL);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,id_agency,beginning,destination,date_start,date_arrive")]
        travel TRAVEL)
        {
            int ID = (Int32)Session["id"];
            int identity = (Int32)Session["identity"];
            if (ModelState.IsValid)
            {
                R.DAL.Context.travel T = new R.DAL.Context.travel()
                {
                    id = identity,
                    id_agency = ID,

                    beginning = TRAVEL.beginning,
                    destination = TRAVEL.destination,
                    date_start = TRAVEL.date_start,
                    date_arrive = TRAVEL.date_arrive,
                    

                };
                db.Entry(T).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Travel");
            }
            ViewBag.beginning = new SelectList(db.villes, "id", "ville_name", TRAVEL.beginning);
            ViewBag.destination = new SelectList(db.villes, "id", "ville_name", TRAVEL.destination);
            return View(TRAVEL);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            travel T = await db.travels.FindAsync(id);

            if (T == null)
            {
                return HttpNotFound();
            }
            
            int ID = (Int32)Session["id"];
            if (T.id_agency!= ID)
            {
                return HttpNotFound();
            }

            travel TT = db.travels
             .Where(i => i.id == id)
             .Single();

            db.travels.Remove(TT);
            db.SaveChanges();
            return RedirectToAction("Travel");
        }






    }
}

AGENCE/Views/Default/Create.cshtml
@model R.DAL.Context.travel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ml-auto d-flex align-items-center secondary-menu text-center">
    <a href="@Url.Action("Travel","Default")" class="tooltip-wrapper">
        <i class="dripicons dripicons-reply" style="font-size: 26px; color:blueviolet"></i>
    </a>
    <br />

</div>
<h2>Create</h2>

@using (Html.BeginForm("Create", "Default", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <!-- start Validation row -->
    <div class="row formavlidation-wrapper">
        <div class="col-xl-6">
            <div class="card card-statistics">
                <div class="card-header">
                    <div class="card-heading">
                        <h4 class="card-title">Create new Travel</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form id="signupForm" method="post" class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label" for="lname">Beginning</label>
                            <div class="mb-2">
                                @Html.DropDownList("beginning", null, htmlAttributes: new { @class = "form-control" })
                                @*<input type="text" class="form-control" id="lname" name="lname" placeholder="Last name" />*@
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="lname">Destination</label>
                            <div class="mb-2">
                                @Html.DropDownList("destination", null, htmlAttributes: new { @class = "form-control" })
                                @*<input type="text" class="form-control" id="lname" name="lname" placeholder="Last name" />*@
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="uname">Start Time</label>
                            <div class="mb-2">

                                @Html.EditorFor(model => model.date_start, new { htmlAttributes = new { @class = "form-control",type="time" } })


                                @*<input type="text" class="form-control" id="uname" name="uname" placeholder="Username" />*@
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="uname">Arrive Time</label>
                            <div class="mb-2">

                                @Html.EditorFor(model => model.date_arrive, new { htmlAttributes = new { @class = "form-control",type="time" } })


                                @*<input type="text" class="form-control" id="uname" name="uname" placeholder="Username" />*@
                            </div>
                        </div>


                        <div class="form-group">

                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">
                                Create
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
}
<!-- end Validation row  -->

AGENCE/Views/Default/Edit.cshtml
@model R.DAL.Context.travel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ml-auto d-flex align-items-center secondary-menu text-center">
    <a href="@Url.Action("Travel","Default")" class="tooltip-wrapper">
        <i class="dripicons dripicons-reply" style="font-size: 26px; color:blueviolet"></i>
    </a>
    <br />



</div>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()



<!-- start Validation row -->
<div class="row formavlidation-wrapper">
    <div class="col-xl-6">
        <div class="card card-statistics">
            <div class="card-header">
                <div class="card-heading">
                    <h4 class="card-title">Edit Travel No.@ViewBag.id</h4>
                </div>
            </div>
            <div class="card-body">
                <form id="signupForm" method="post" class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label" for="lname">Beginning</label>
                        <div class="mb-2">
                            @Html.DropDownList("beginning", null, htmlAttributes: new { @class = "form-control" })
                            @*<input type="text" class="form-control" id="lname" name="lname" placeholder="Last name" />*@
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="lname">Destination</label>
                        <div class="mb-2">
                            @Html.DropDownList("destination", null, htmlAttributes: new { @class = "form-control" })
                            @*<input type="text" class="form-control" id="lname" name="lname" placeholder="Last name" />*@
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="uname">Start Time</label>
                        <div class="mb-2">

                            @Html.EditorFor(model => model.date_start, new { htmlAttributes = new { @class = "form-control", type = "time" } })


                            @*<input type="text" class="form-control" id="uname" name="uname" placeholder="Username" />*@
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="uname">Arrive Time</label>
                        <div class="mb-2">

                            @Html.EditorFor(model => model.date_arrive, new { htmlAttributes = new { @class = "form-control", type = "time" } })


                            @*<input type="text" class="form-control" id="uname" name="uname" placeholder="Username" />*@
                        </div>
                    </div>
                   

                    <div class="form-group">

                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            Edit
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
</div>
}
<!-- end Validation row  -->

AGENCE/Views/Default/Index.cshtml
@model R.DAL.Context.travel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

AGENCE/Views/Default/Travel.cshtml
@model IEnumerable<R.DAL.Context.travel>

@{
    ViewBag.Title = "Travel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="text-align:center">
    <h2>TRAVELS</h2>
</div>



<div class="ml-auto d-flex align-items-center secondary-menu text-center">
    <a href="@Url.Action("Create","Default")" class="tooltip-wrapper">
        <i class="fe fe-edit btn btn-icon text-primary"></i>
    </a>
    <br />



</div>
<table class="table">
    <tr>
        
        <th>
            Beginning
        </th>
        <th>
            Destination
        </th>
        <th>
            Start
        </th>
        <th>
            Arrive
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.ville.ville_name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.ville1.ville_name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.date_start)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.date_arrive)
        </td>
        
        <td>
            <a href="@Url.Action("Delete", "Default",new {id=item.id})" class="confirmation">
                <i class="dashicons dashicons-trash" style="font-size: 20px; color: #c90404"></i>
            </a>
             | 
            <a href="@Url.Action("Edit", "Default",new {id=item.id})" class="confirmation">
                <i class="dashicons dashicons-edit" style="font-size: 20px; color: #ede61a "></i>
            </a>
            @*@Html.ActionLink("DELETE", "Delete", new { id = item.id })|
            @Html.ActionLink("EDIT", "Edit", new { id = item.id })*@
        </td>
    </tr>
}

</table>